export const SET_SCHEDULES = 'SCHEDULES/SET_SCHEDULES'

// SCHEDULES
export const SET_WORKLOAD = 'SCHEDULES/SET_WORKLOAD'
export const SET_UNAVAILABLE = 'SCHEDULES/SET_UNAVAILABLE'
export const SET_NAME_TEACHER = 'SCHEDULES/SET_NAME_TEACHER'
export const SET_NAME_DISCIPLINE = 'SCHEDULES/SET_NAME_DISCIPLINE'
